Script started on Sat 26 Nov 2016 07:04:47 PM UTC
[01;32mmanley1971[00m:[01;34m~/workspace/python-getting-started/hello/templates[00m (master) $ v[Kgit push [K[K[K[K[Kcommit -am "shane changes"
[master 7839333] shane changes
 1 file changed, 2 insertions(+), 2 deletions(-)
[01;32mmanley1971[00m:[01;34m~/workspace/python-getting-started/hello/templates[00m (master) $ git push heroku master
Counting objects: 5, done.
Delta compression using up to 8 threads.
Compressing objects:  20% (1/5)   Compressing objects:  40% (2/5)   Compressing objects:  60% (3/5)   Compressing objects:  80% (4/5)   Compressing objects: 100% (5/5)   Compressing objects: 100% (5/5), done.
Writing objects:  20% (1/5)   Writing objects:  40% (2/5)   Writing objects:  60% (3/5)   Writing objects:  80% (4/5)   Writing objects: 100% (5/5)   Writing objects: 100% (5/5), 477 bytes | 0 bytes/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Compressing source files... done.[K
remote: Building source:[K
remote: 
remote: -----> Python app detected[K
remote:      $ pip install -r requirements.txt[K
remote: 
remote:      $ python manage.py collectstatic --noinput[K
remote:        58 static files copied to '/app/gettingstarted/staticfiles', 58 post-processed.[K
remote: 
remote: -----> Discovering process types[K
remote:        Procfile declares types -> web[K
remote: 
remote: -----> Compressing...[K
remote:        Done: 42.9M[K
remote: -----> Launching...[K
remote:        Released v6[K
remote:        https://manley-video-parser.herokuapp.com/ deployed to Heroku[K
remote: 
remote: Verifying deploy... done.[K
To https://git.heroku.com/manley-video-parser.git
   e707ac4..7839333  master -> master
[01;32mmanley1971[00m:[01;34m~/workspace/python-getting-started/hello/templates[00m (master) $ ed s[K[K[K[Kexit

Script done on Sat 26 Nov 2016 07:07:32 PM UTC
